# Generated by Django 4.2.1 on 2023-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
