# Generated by Django 4.2.1 on 2023-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="end_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="start_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
