# Generated by Django 4.2.1 on 2023-05-12 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_hackathonparticipant_submission_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
